### ISSUE TITLE
telescope命令行详情无响应/服务重启

### ISSUE THREAD

**Issue by tw2066** [friendsofhyperf/components#524]
telescope最新版本

```
composer require friendsofhyperf/telescope:~3.1.0
```
查看命令行详情
请求地址: http://127.0.0.1:9509/telescope/commands/018d58f6-6180-73a6-9d70-611af1c7bef5
报错信息
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /WWW/php-service/vendor/hyperf/database/src/Connection.php on line 275

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /WWW/php-service/vendor/hyperf/database/src/Connection.php on line 275
[2024-01-30 14:07:02 *39447.0]	ERROR	php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /WWW/php-service/vendor/hyperf/database/src/Connection.php on line 275
[2024-01-30 14:07:02 @39447.0]	WARNING	Channel::~Channel() (ERRNO 10003): channel is destroyed, 3 consumers will be discarded
[2024-01-30 14:07:02 $39445.0]	WARNING	Server::check_worker_exit_status(): worker(pid=39447, id=0) abnormal exit, status=255, signal=0
2024-01-30 14:07:02.881 [INFO] [WorkerStartCallback::onWorkerStart] Worker#0 started.
2024-01-30 14:07:02.881 [INFO] [AfterWorkerStartListener::process] HTTP Server listening at 0.0.0.0:9509
2024-01-30 14:07:02.882 [INFO] [AfterWorkerStartListener::process] HTTP Server listening at 0.0.0.0:19587
2024-01-30 14:07:02.882 [INFO] [AfterWorkerStartListener::process] HTTP Server listening at 0.0.0.0:9501

```

**Comment by tw2066** [comment]
执行到 EntryController.php 84行
```
$batch = $query->with('tags')->orderByDesc('sequence')->get();
```
会超内存

**Comment by guandeng** [comment]
只有command报错？





------------------ 原始邮件 ------------------
发件人: Mr.唐 ***@***.***&gt;
发送时间: 2024年1月30日 14:19
收件人: friendsofhyperf/components ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [friendsofhyperf/components] telescope命令行详情无响应/服务重启 (Issue #524)





 
执行到 EntryController.php 84行
 $batch = $query-&gt;with('tags')-&gt;orderByDesc('sequence')-&gt;get();  
会超内存

**Comment by tw2066** [comment]
redis详情也会

**Comment by tw2066** [comment]
> 执行到 EntryController.php 84行
> 
> ```
> $batch = $query->with('tags')->orderByDesc('sequence')->get();
> ```
> 
> 会超内存

batch_id为空
生成sql
```
select * from `telescope_entries` where `batch_id` = '' order by `sequence` desc
```
共计2W多条

**Comment by guandeng** [comment]
> > 执行到 EntryController.php 84行
> > ```
> > $batch = $query->with('tags')->orderByDesc('sequence')->get();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 会超内存
> 
> batch_id为空 生成sql
> 
> ```
> select * from `telescope_entries` where `batch_id` = '' order by `sequence` desc
> ```
> 
> 共计2W多条

排查一下业务代码是不是频繁调用redis  模式改一下save_mode' => Telescope::ASYNC

**Comment by guandeng** [comment]
> > > 执行到 EntryController.php 84行
> > > ```
> > > $batch = $query->with('tags')->orderByDesc('sequence')->get();
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 会超内存
> > 
> > 
> > batch_id为空 生成sql
> > ```
> > select * from `telescope_entries` where `batch_id` = '' order by `sequence` desc
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 共计2W多条
> 
> 排查一下业务代码是不是频繁调用redis 模式改一下save_mode' => Telescope::ASYNC

有操作吗，问题复现可以加我v  fanguandeng

**Comment by tw2066** [comment]
设置 Telescope::ASYNC  可以解决

**Comment by guandeng** [comment]
> > 执行到 EntryController.php 84行
> > ```
> > $batch = $query->with('tags')->orderByDesc('sequence')->get();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 会超内存
> 
> batch_id为空 生成sql
> 
> ```
> select * from `telescope_entries` where `batch_id` = '' order by `sequence` desc
> ```
> 
> 共计2W多条



> > 执行到 EntryController.php 84行
> > ```
> > $batch = $query->with('tags')->orderByDesc('sequence')->get();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 会超内存
> 
> batch_id为空 生成sql
> 
> ```
> select * from `telescope_entries` where `batch_id` = '' order by `sequence` desc
> ```
> 
> 共计2W多条

batch_id为空已补上#533
